// Generated by python -m scientist.contracts; do not edit.

export interface Principal {
  identity: string;
  kind: "owner" | "external" | "worker";
}

export interface APIError {
  code: string;
  message: string;
  request_id: string;
}

export interface ObjectRef {
  project_id: string;
  key: string;
  sha256: string;
  size: number;
  content_type: string;
}

export interface PackageSpec {
  name: string;
  version: string;
  source: string;
  sha256: string;
}

export interface PlanSpec {
  input_snapshot_digest: string;
  provider_id: string;
  model: string;
  stages: string[];
  allowed_ops: string[];
  data_recipients: string[];
  packages: PackageSpec[];
  token_limit: number;
  elapsed_limit_ms: number;
}

export interface ArtifactView {
  artifact_id: string;
  project_id: string;
  run_id: string;
  title: string;
  kind: "report" | "table" | "plot" | "file";
  sha256: string;
  size: number;
  content_type: string;
  partial: boolean;
}

export interface PlanView {
  run_id: string;
  revision: number;
  plan_digest: string;
  plan: PlanSpec;
}

export interface RunView {
  run_id: string;
  project_id: string;
  session_id: string;
  revision: number;
  state: "planning" | "awaiting_approval" | "queued" | "running" | "waiting_input" | "recovering" | "stopping" | "completed" | "failed" | "canceled" | "rejected";
  stage?: null | string;
  waiting_reason?: null | string;
  error_code?: null | string;
  plan_digest?: null | string;
  latest_cursor: number;
  usage_tokens: number;
  reserved_tokens: number;
  planning_tokens: number;
  token_limit: number;
  artifacts: ArtifactView[];
}

export interface OperationRequest {
  run_id: string;
  generation: number;
  operation_id: string;
  kind: "llm" | "search" | "package" | "peer";
  payload: Record<string, unknown>;
  reserve_tokens: number;
}

export interface OperationResult {
  operation_id: string;
  state: "committed" | "unknown" | "denied";
  result: ObjectRef | null;
  usage_tokens?: null | number;
}

export interface CheckpointManifest {
  schema_version: number;
  run_id: string;
  revision: number;
  plan_digest: string;
  runtime_commit: string;
  image_digest: string;
  skills_digest: string;
  context: ObjectRef;
  workspace: ObjectRef[];
  environment_digest: string;
  operation_ids: string[];
}

export interface ProjectView {
  id: string;
  name: string;
  revision: number;
  instructions: string;
}

export interface SessionView {
  id: string;
  project_id: string;
  title: string;
}

export interface FileView {
  id: string;
  project_id: string;
  filename: string;
  size: number;
  content_type: string;
  state: "uploading" | "preparing" | "ready" | "failed";
  error_code?: null | string;
}

export interface FindingView {
  id: string;
  project_id: string;
  session_id: string;
  artifact_id?: null | string;
  text: string;
  citation_ids: string[];
}

export interface CitationView {
  id: string;
  title: string;
  authors: string[];
  year?: null | number;
  identifier?: null | string;
  original_url?: null | string;
  access?: "full_text" | "abstract" | "metadata" | "unavailable" | null;
  verification?: "verified" | "unverified" | "contradictory" | null;
}

export interface ConnectionView {
  id: string;
  label: string;
  provider: string;
  model: string;
  state: "unconfigured" | "checking" | "ready" | "invalid_credentials" | "unavailable_provider" | "unavailable_model";
  has_secret: boolean;
}

export interface MessageView {
  id: string;
  sequence: number;
  role: string;
  content: string;
  created_at: string;
  run_id?: null | string;
}

export interface DecisionSubmit {
  decision_id: string;
  expected_revision: number;
  idempotency_key: string;
  choice: "verified_result" | "retry" | "stop" | "extend";
  result?: ObjectRef | null;
  add_tokens?: null | number;
  add_elapsed_ms?: null | number;
}

export interface PlanReadyPayload {
  plan_digest: string;
}

export interface RunStatePayload {
  state: "planning" | "awaiting_approval" | "queued" | "running" | "waiting_input" | "recovering" | "stopping" | "completed" | "failed" | "canceled" | "rejected";
}

export interface StageStartedPayload {
  stage: string;
}

export interface StageCompletedPayload {
  stage: string;
  outcome: "completed" | "partial" | "failed";
}

export interface ArtifactReadyPayload {
  artifact: ArtifactView;
}

export interface DecisionRequiredPayload {
  decision_id: string;
  reason: "budget_exhausted" | "unknown_outcome" | "data_scope" | "plan_change";
  required_tokens?: null | number;
  required_elapsed_ms?: null | number;
}

export interface UsageUpdatedPayload {
  usage_tokens: number;
  reserved_tokens: number;
  token_limit: number;
}

export type RunEvent = { schema_version: 1; run_id: string; sequence: number; revision: number; occurred_at: string; kind: "plan.ready"; payload: PlanReadyPayload } | { schema_version: 1; run_id: string; sequence: number; revision: number; occurred_at: string; kind: "run.state"; payload: RunStatePayload } | { schema_version: 1; run_id: string; sequence: number; revision: number; occurred_at: string; kind: "stage.started"; payload: StageStartedPayload } | { schema_version: 1; run_id: string; sequence: number; revision: number; occurred_at: string; kind: "stage.completed"; payload: StageCompletedPayload } | { schema_version: 1; run_id: string; sequence: number; revision: number; occurred_at: string; kind: "artifact.ready"; payload: ArtifactReadyPayload } | { schema_version: 1; run_id: string; sequence: number; revision: number; occurred_at: string; kind: "decision.required"; payload: DecisionRequiredPayload } | { schema_version: 1; run_id: string; sequence: number; revision: number; occurred_at: string; kind: "usage.updated"; payload: UsageUpdatedPayload };
