// Generated by python -m scientist.contracts; do not edit.

export interface RuntimePins {
  runtime_commit?: string;
  image_digest: string;
  skills_digest: string;
  environment_digest: string;
}

export interface ScientificBinding {
  catalog_commit: "154988403bb5a18e9d3c0ce4e6d5e2e4b184a298";
  registry_sha256: string;
  capability_ids: string[];
  instruction_fingerprint: string;
  profile_id: string;
  profile_version?: "1";
  image_digest: string;
  tool_version?: "1";
  input_snapshot_digest: string;
  parameters?: Record<string, unknown>;
  max_result_bytes: number;
  timeout_ms: number;
  memory_limit_bytes: number;
  workspace_limit_bytes: number;
}

export interface ScientificBindingV2 {
  binding_version: 2;
  catalog_commit: "154988403bb5a18e9d3c0ce4e6d5e2e4b184a298";
  registry_sha256: string;
  capability_ids: string[];
  instruction_fingerprint: string;
  agent_runtime_pins: RuntimePins;
  input_snapshot_digest: string;
  approved_crossref_queries?: Record<string, CrossrefQueryV1>;
  required_compute_profiles?: ComputeProfilePin[];
  csv_describe_grants?: Record<string, CsvDescribeGrantV1>;
}

export interface CrossrefQueryV1 {
  source_id: "crossref";
  version: 1;
  access_mode: "public_read";
  query: null | string;
  doi: null | string;
  limit: number;
}

export interface CsvResearchSelection {
  crossref: CrossrefQueryV1;
  csv_file_id: string;
  numeric_columns: string[];
}

export interface CsvDescribeGrantV1 {
  recipe_id: "csv.describe.v1";
  recipe_version: "1";
  recipe_manifest_sha256: string;
  profile_id: "prof.csv-stdlib@py3.14.7";
  profile_version: "1";
  image_digest: string;
  input_ref: ObjectRef;
  input_sha256: string;
  numeric_columns: string[];
  max_input_bytes?: 1048576;
  max_output_bytes?: 262144;
  timeout_ms?: 30000;
  memory_limit_bytes?: 1073741824;
  workspace_limit_bytes?: 67108864;
}

export interface ComputeProfilePin {
  profile_id: "prof.csv-stdlib@py3.14.7";
  version: "1";
  image_digest: string;
}

export interface ResearchRequirementView {
  id: string;
  label: string;
  purpose: string;
  state: "ready" | "missing" | "preparing" | "blocked" | "failed";
  action: "none" | "configure_connection" | "prepare_environment" | "request_approval" | "provide_hardware";
  reason?: null | string;
}

export interface ResearchProfileView {
  profile_id: string;
  version: string;
  manifest_sha256: string;
  label: string;
  purpose: string;
  state: "ready" | "missing" | "preparing" | "blocked" | "failed";
  memory_limit_bytes: number;
  workspace_limit_bytes: number;
  reason?: null | string;
}

export interface PreparationSubmit {
  profile_id: string;
  version: string;
  manifest_sha256: string;
  request_id: string;
}

export interface PreparationJobView {
  id: string;
  project_id: string;
  profile_id: string;
  version: string;
  manifest_sha256: string;
  state: "queued" | "building" | "checking" | "ready" | "blocked" | "failed" | "unknown";
  stage: "queued" | "context" | "image" | "compatibility" | "security" | "license" | "isolation" | "complete" | "owner_decision";
  error_code?: null | string;
  evidence_verified?: boolean;
}

export interface ResearchSetupView {
  project_id: string;
  requirements: ResearchRequirementView[];
  profiles: ResearchProfileView[];
  connections: ConnectionView[];
  preparations: PreparationJobView[];
}

export interface RunReadinessView {
  run_id: string;
  revision: number;
  plan_digest: string;
  binding_sha256?: null | string;
  state: "ready" | "missing" | "preparing" | "blocked" | "failed";
  requirements: ResearchRequirementView[];
}

export interface Principal {
  identity: string;
  kind: "owner" | "external" | "worker";
}

export interface APIError {
  code: string;
  message: string;
  request_id: string;
}

export interface ObjectRef {
  project_id: string;
  key: string;
  sha256: string;
  size: number;
  content_type: string;
}

export interface PackageSpec {
  name: string;
  version: string;
  source: string;
  sha256: string;
}

export interface PeerDataRef {
  kind: "file" | "finding";
  record_id: string;
  version_digest: string;
}

export interface PeerReleaseSpec {
  release_id: string;
  peer_id: string;
  endpoint_fingerprint: string;
  purpose: string;
  input_snapshot_digest: string;
  data_refs?: PeerDataRef[];
  approved_parameters: Record<string, unknown>;
  parameters_sha256: string;
  message_id: string;
  method?: "SendMessage";
  allow_get_task?: boolean;
  request_bytes_limit: number;
  timeout_ms: number;
  reserved_tokens: number;
  reconciliation_limit: number;
}

export interface PlanSpec {
  input_snapshot_digest: string;
  provider_id: string;
  model: string;
  stages: string[];
  allowed_ops: string[];
  data_recipients: string[];
  packages: PackageSpec[];
  peer_releases?: PeerReleaseSpec[];
  scientific?: ScientificBinding | ScientificBindingV2 | null;
  token_limit: number;
  elapsed_limit_ms: number;
}

export interface ArtifactView {
  artifact_id: string;
  project_id: string;
  run_id: string;
  title: string;
  kind: "report" | "table" | "plot" | "file";
  sha256: string;
  size: number;
  content_type: string;
  partial: boolean;
}

export interface PlanView {
  run_id: string;
  revision: number;
  plan_digest: string;
  plan: PlanSpec;
}

export interface RunView {
  run_id: string;
  project_id: string;
  session_id: string;
  revision: number;
  state: "planning" | "awaiting_approval" | "queued" | "running" | "waiting_input" | "recovering" | "stopping" | "completed" | "failed" | "canceled" | "rejected";
  stage?: null | string;
  waiting_reason?: null | string;
  error_code?: null | string;
  plan_digest?: null | string;
  latest_cursor: number;
  usage_tokens: number;
  reserved_tokens: number;
  planning_tokens: number;
  token_limit: number;
  artifacts: ArtifactView[];
  retry_of?: null | string;
}

export interface PendingDecisionView {
  decision_id: string;
  reason: "budget_exhausted" | "unknown_outcome" | "data_scope" | "plan_change";
  required_tokens?: null | number;
  required_elapsed_ms?: null | number;
  operation_reserved_tokens?: null | number;
}

export interface OperationRequest {
  run_id: string;
  generation: number;
  operation_id: string;
  kind: "llm" | "search" | "package" | "peer" | "compute";
  payload: Record<string, unknown>;
  reserve_tokens: number;
}

export interface OperationResult {
  operation_id: string;
  state: "committed" | "unknown" | "denied";
  result: ObjectRef | null;
  usage_tokens?: null | number;
}

export interface CheckpointManifest {
  schema_version: number;
  run_id: string;
  revision: number;
  plan_digest: string;
  runtime_commit: string;
  image_digest: string;
  skills_digest: string;
  context: ObjectRef;
  workspace: ObjectRef[];
  environment_digest: string;
  operation_ids: string[];
}

export interface ProjectView {
  id: string;
  name: string;
  revision: number;
  instructions: string;
}

export interface SessionView {
  id: string;
  project_id: string;
  title: string;
}

export interface FileView {
  id: string;
  project_id: string;
  filename: string;
  size: number;
  content_type: string;
  state: "uploading" | "preparing" | "ready" | "failed";
  error_code?: null | string;
}

export interface FindingView {
  id: string;
  project_id: string;
  session_id: string;
  artifact_id?: null | string;
  text: string;
  citation_ids: string[];
}

export interface CitationView {
  id: string;
  title: string;
  authors: string[];
  year?: null | number;
  identifier?: null | string;
  original_url?: null | string;
  access?: "full_text" | "abstract" | "metadata" | "unavailable" | null;
  verification?: "verified" | "unverified" | "contradictory" | null;
}

export interface ConnectionView {
  id: string;
  label: string;
  provider: string;
  model: string;
  state: "unconfigured" | "checking" | "ready" | "invalid_credentials" | "unavailable_provider" | "unavailable_model";
  has_secret: boolean;
}

export interface MessageView {
  id: string;
  sequence: number;
  role: string;
  content: string;
  created_at: string;
  run_id?: null | string;
}

export interface DecisionSubmit {
  decision_id: string;
  expected_revision: number;
  idempotency_key: string;
  choice: "verified_result" | "retry" | "stop" | "extend" | "confirm_usage";
  result?: ObjectRef | null;
  add_tokens?: null | number;
  add_elapsed_ms?: null | number;
  usage_tokens?: null | number;
}

export interface PlanReadyPayload {
  plan_digest: string;
}

export interface RunStatePayload {
  state: "planning" | "awaiting_approval" | "queued" | "running" | "waiting_input" | "recovering" | "stopping" | "completed" | "failed" | "canceled" | "rejected";
}

export interface StageStartedPayload {
  stage: string;
}

export interface StageCompletedPayload {
  stage: string;
  outcome: "completed" | "partial" | "failed";
}

export interface ArtifactReadyPayload {
  artifact: ArtifactView;
}

export interface DecisionRequiredPayload {
  decision_id: string;
  reason: "budget_exhausted" | "unknown_outcome" | "data_scope" | "plan_change";
  required_tokens?: null | number;
  required_elapsed_ms?: null | number;
}

export interface UsageUpdatedPayload {
  usage_tokens: number;
  reserved_tokens: number;
  token_limit: number;
}

export type RunEvent = { schema_version: 1; run_id: string; sequence: number; revision: number; occurred_at: string; kind: "plan.ready"; payload: PlanReadyPayload } | { schema_version: 1; run_id: string; sequence: number; revision: number; occurred_at: string; kind: "run.state"; payload: RunStatePayload } | { schema_version: 1; run_id: string; sequence: number; revision: number; occurred_at: string; kind: "stage.started"; payload: StageStartedPayload } | { schema_version: 1; run_id: string; sequence: number; revision: number; occurred_at: string; kind: "stage.completed"; payload: StageCompletedPayload } | { schema_version: 1; run_id: string; sequence: number; revision: number; occurred_at: string; kind: "artifact.ready"; payload: ArtifactReadyPayload } | { schema_version: 1; run_id: string; sequence: number; revision: number; occurred_at: string; kind: "decision.required"; payload: DecisionRequiredPayload } | { schema_version: 1; run_id: string; sequence: number; revision: number; occurred_at: string; kind: "usage.updated"; payload: UsageUpdatedPayload };
